# ⚑ Site - Basics
# Site title
title: "The_R Games"

# Site author
author: "Rohan Narang"

# Site copyright year
year: 2014

# Site logo (partial-URL relative to /img/)
logo: "logo/pastels-logo.png"

# Site sub-title
subtitle: "Game Development Blog"

# A short description for the site
description: "Hi! I'm Rohan, an Indie Game Developer."





# ⚑ Site - Advanced
# Social media
social:
  # Author's Twitter handle
  twitter: "rohan_narang15"

  # Author's Github handle
  github: "thergames"

  # Author's Facebook handle
  facebook: "rohan.narang.96"

  # Author's disqus short name
  disqus: ""





# ⚑ Jekyll configuration
markdown: redcarpet
pygments: true
exclude: ["bower.json", "config.rb", "*.sublime*", "readme.md", "license.md", "css/main.scss"]
